apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app-container
          image: us-central1-docker.pkg.dev/$PROJECT_ID/web-app/web-app:0.0.2
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
